///
/// @file Antlr4ParseListener.hpp
/// @author Peeter Joot <peeterjoot@pm.me>
/// @brief Antlr4 based Listener and MLIR builder for the silly compiler.
///
/// This class processes the parse tree generated by the Silly grammar, building
/// corresponding MLIR operations in the Silly dialect. It tracks variable states
/// per function, handles scoping, control flow (if/for), declarations, assignments,
/// function calls, and built-in operations (print/get/exit/return).
///
#pragma once

#include <antlr4-runtime.h>
#include <mlir/IR/Location.h>
#include <mlir/IR/MLIRContext.h>

#include <format>
#include <map>
#include <unordered_map>
#include <vector>

#include "Builder.hpp"
#include "DriverState.hpp"
#include "LocationStack.hpp"
#include "MlirTypeCache.hpp"
#include "ParserPerFunctionState.hpp"
#include "PrintFlags.hpp"
#include "SillyBaseListener.h"
#include "SillyDialect.hpp"

namespace silly
{
    /// antlr4::tree::TerminalNode is a long winded expression
    using tNode = antlr4::tree::TerminalNode;

    /// ANTLR listener that constructs MLIR for the Silly language.
    ///
    /// Inherits from SillyBaseListener and BaseErrorListener to process parse tree
    /// events and report syntax errors. Builds a ModuleOp containing FuncOps
    /// with Silly dialect operations.
    class Antlr4ParseListener : public Builder, SillyBaseListener, antlr4::BaseErrorListener
    {
       public:
        /// Constructor.
        /// @param s [in] Owning SourceManager (used for IMPORT module lookup.)
        /// @param filename [in] Source filename for this module (used to construct Location info)
        Antlr4ParseListener( silly::SourceManager& s, const std::string& filename );

        /// Open the file stream, and walk the parse tree.
        ///
        /// Will set DriverState::openFailed for early pre-parse stream open error (with nullptr return.)
        ///
        /// If DriverState::openFailed is false, then a non-nullptr return means that no compilation errors occured, and
        /// the MLIR builder was successful.  FIXME: need a sema pass.  That should happen after this builder return.
        ///
        mlir::OwningOpRef<mlir::ModuleOp> run();

        /// Override to throw on syntax errors.
        void syntaxError( antlr4::Recognizer* recognizer, antlr4::Token* offendingSymbol, size_t line,
                          size_t charPositionInLine, const std::string& msg, std::exception_ptr e ) override;

        /// Antlr4 enter hook for the start rule.
        void enterStartRule( SillyParser::StartRuleContext* ctx ) override;

        /// Antlr4 exit hook for the start rule.
        void exitStartRule( SillyParser::StartRuleContext* ctx ) override;

        /// Antlr4 entry hook for the scopedStatements rule.
        void enterScopedStatements( SillyParser::ScopedStatementsContext* ctx ) override;

        /// Antlr4 exit hook for the scopedStatements rule.
        void exitScopedStatements( SillyParser::ScopedStatementsContext* ctx ) override;

        /// Antlr4 entry hook for the ImportStatementContext rule.
        void enterImportStatement( SillyParser::ImportStatementContext* ctx ) override;

        /// Antlr4 enter hook for an ELIF statement
        void enterElifStatement( SillyParser::ElifStatementContext* ctx ) override;

        /// Antlr4 enter hook for an ELSE statement
        void enterElseStatement( SillyParser::ElseStatementContext* ctx ) override;

        /// Antlr4 enter hook for an IF-ELIF-ELSE statement.
        void enterIfElifElseStatement( SillyParser::IfElifElseStatementContext* ctx ) override;

        /// Antlr4 exit hook for an IF-ELIF-ELSE statement.
        ///
        /// Restore EXACTLY where we were before creating the IF
        /// This places new ops right AFTER the IF
        void exitIfElifElseStatement( SillyParser::IfElifElseStatementContext* ctx ) override;

        /// Antlr4 enter hook for a functionStatement rule.
        void enterFunctionStatement( SillyParser::FunctionStatementContext* ctx ) override;
        /// Antlr4 exit hook for a functionStatement rule.
        void exitFunctionStatement( SillyParser::FunctionStatementContext* ctx ) override;

        /// Antlr4 enter hook for a callStatement rule.
        void enterCallStatement( SillyParser::CallStatementContext* ctx ) override;

        /// Antlr4 enter hook for a returnStatement rule.
        void enterReturnStatement( SillyParser::ReturnStatementContext* ctx ) override;

        /// Antlr4 enter hook for a boolDeclareStatement rule.
        void enterBoolDeclareStatement( SillyParser::BoolDeclareStatementContext* ctx ) override;

        /// Antlr4 enter hook for an intDeclareStatement rule.
        void enterIntDeclareStatement( SillyParser::IntDeclareStatementContext* ctx ) override;

        /// Antlr4 enter hook for a floatDeclareStatement rule.
        void enterFloatDeclareStatement( SillyParser::FloatDeclareStatementContext* ctx ) override;

        /// Antlr4 enter hook for a stringDeclareStatement rule.
        void enterStringDeclareStatement( SillyParser::StringDeclareStatementContext* ctx ) override;

        /// Antlr4 enter hook for a printStatement rule.
        void enterPrintStatement( SillyParser::PrintStatementContext* ctx ) override;

        /// Antlr4 enter hook for an errorStatement rule.
        void enterErrorStatement( SillyParser::ErrorStatementContext* ctx ) override;

        /// Antlr4 enter hook for an abortStatement rule.
        void enterAbortStatement( SillyParser::AbortStatementContext* ctx ) override;

        /// Antlr4 enter hook for a getStatement rule.
        void enterGetStatement( SillyParser::GetStatementContext* ctx ) override;

        /// Antlr4 enter hook for a forStatement rule.
        void enterForStatement( SillyParser::ForStatementContext* ctx ) override;

        /// Antlr4 exit hook for a forStatement rule.
        void exitForStatement( SillyParser::ForStatementContext* ctx ) override;

        /// Antlr4 enter hook for an assignmentStatement rule.
        void enterAssignmentStatement( SillyParser::AssignmentStatementContext* ctx ) override;

        /// Antlr4 enter hook for an exitStatement rule.
        void enterExitStatement( SillyParser::ExitStatementContext* ctx ) override;

       private:
        //----------------------------------------------------------------------
        //
        // Helper functions
        //
        //----------------------------------------------------------------------

        /// Parse the IF/ELIF predicate, creating an mlir::Value, and create the conditional branch
        ///
        /// @retval true if error.
        bool createIfPredicate( SillyParser::ExpressionContext* ctx, silly::ScopeEndOp scopeEnd, mlir::Block* ifBlock,
                                mlir::Block* elseBlock, LocationStack& ls );

        /// Check that there is no RETURN statement and create an IF body scope.
        ///
        /// Side effect: changes the insertion point.
        void handleIfScopedStatements( InsertionPointState& ips, ParserPerFunctionState& f,
                                       SillyParser::ScopedStatementsContext* ss, const char* scopeCheckString,
                                       mlir::Block* bodyBlock, mlir::Block* targetBlock );

        /// Parse a RETURN expression, if there is one.
        ///
        /// Also checks that function is supposed to have a RETURN value, if the input return expression was provided.
        mlir::Value parseReturnExpression( mlir::Location loc, SillyParser::ExpressionContext* expression,
                                           LocationStack& ls );

        /// @brief check for inappropriate RETURN
        ///
        /// Grammar now allows for RETURN in IF/ELIF/ELSE/FOR blocks, (as well as FUNCTION)
        /// but that is not supported.  Check for that explicitly, and raise a user error,
        /// instead of just letting this fail mysteriously in lowering.
        void checkForReturnInScope( SillyParser::ScopedStatementsContext* scope, const char* what );

        /// Lookup and validate a declareStatement variable name, and process the declaration.
        void enterDeclareHelper( mlir::Location loc, tNode* identifier, bool hasInitializer,
                                 const std::vector<SillyParser::ExpressionContext*>& expressions,
                                 SillyParser::ArrayBoundsExpressionContext* arrayBoundsExpression, mlir::Type ty,
                                 LocationStack& ls );

        /// Construct locations from the getStart() and getStop() tokens.
        inline LocPairs getLocations( antlr4::ParserRuleContext* ctx, bool unique = false );

        /// Computes start location from parser context.
        inline mlir::Location getStartLocation( antlr4::ParserRuleContext* ctx );

        /// Computes stop location from parser context.
        inline mlir::Location getStopLocation( antlr4::ParserRuleContext* ctx );

        /// Build a Location for an antlr4 Token.
        inline mlir::Location getTokenLocation( antlr4::Token* token );

        /// Build a Location for an antlr4 tNode
        inline mlir::Location getTerminalLocation( tNode* node );

        /// Emits a CallOp for a function call.
        mlir::Value parseCallStatementOrExpr( SillyParser::CallExpressionContext* ctx, bool callStatement,
                                              LocationStack& ls );

        /// builder logic for print arguments (shared between PRINT and ERROR.)
        void handlePrint( mlir::Location loc, const std::vector<SillyParser::ExpressionContext*>& args,
                          const std::string& errorContextString, PrintFlags flags, LocationStack& ls );

        /// Map INT8_TOKEN, INT16_TOKEN, ... to a mlir::Type
        mlir::Type integerDeclarationType( mlir::Location loc, SillyParser::IntTypeContext* ctx );

        /// Parses scalar type string to MLIR type.
        mlir::Type parseScalarType( const std::string& ty );

        /// Handle parsing of an expression (the top-level entry point for expressions).
        /// This function serves as the main entry point for parsing any rvalue expression.
        /// It delegates to the lowest-precedence level (logical OR).
        /// @param ctx The ExpressionContext from the parser (contains expression())
        /// @param ty Type override
        /// @return The MLIR Value representing the parsed expression
        inline mlir::Value parseExpression( SillyParser::ExpressionContext* ctx, mlir::Type ty, LocationStack& ls );

        /// calls parseOr, first actual expression level in the hierarchy
        inline mlir::Value parseLowest( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the logical OR level (lowest precedence binary operator).
        /// Handles expressions of the form: expr OR expr OR expr ...
        /// Left-associative folding. If no OR is present, descends to the AND level.
        /// @param ctx The ExpressionContext (usually ExprLowestContext)
        /// @param ty Type override
        /// @return The resulting Value (typically i1 for logical OR)
        mlir::Value parseOr( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Look for a XorExprContext, and handle it if found.
        mlir::Value parseXor( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the logical AND level.
        /// Handles expressions of the form: term AND term AND term ...
        /// Left-associative. Falls through to equality level if no AND operators are present.
        /// @param ctx BinaryExpressionAndContext from the parser
        /// @param ty type override
        /// @return The resulting Value (typically i1 for logical AND)
        mlir::Value parseAnd( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the equality/inequality level (== and != operators).
        /// Handles expressions of the form: cmp == cmp != cmp ...
        /// Left-associative. Falls through to comparison level if no equality operators.
        /// @param ctx BinaryExpressionCompareContext (may be EqNeExprContext when operators present)
        /// @param ty type override
        /// @return The resulting Value (typically i1 for comparisons)
        mlir::Value parseEquality( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the comparison level (< > <= >=).
        /// Handles expressions of the form: add < add > add <= add ...
        /// Left-associative. Falls through to additive level if no comparison operators.
        /// @param ctx BinaryExpressionCompareContext (CompareExprContext when operators present)
        /// @param ty type override
        /// @return The resulting Value (typically i1)
        mlir::Value parseComparison( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the additive level (+ and - operators).
        /// Handles expressions of the form: mul + mul - mul ...
        /// Left-associative. Falls through to multiplicative level if no +/−.
        /// @param ctx BinaryExpressionAddSubContext
        /// @param ty type override
        /// @return The resulting Value
        mlir::Value parseAdditive( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse the multiplicative level (* and / operators).
        /// Handles expressions of the form: unary * unary / unary ...
        /// Left-associative. Falls through to unary level if no * or /.
        /// @param ctx BinaryExpressionMulDivContext
        /// @param ty type override
        /// @return The resulting Value
        mlir::Value parseMultiplicative( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse unary operators (negation, NOT, etc.).
        /// Handles expressions of the form: - unary, NOT unary, or primary.
        /// Right-associative for multiple unaries (e.g., --x).
        /// @param ctx UnaryExpressionContext
        /// @param ty type override
        /// @return The resulting Value
        mlir::Value parseUnary( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );

        /// Parse primary expressions (literals, variables, calls, parenthesized expressions).
        /// The leaves of the expression tree:
        ///   - literals (integer, float, boolean, string)
        ///   - scalarOrArrayElement (variables or array indexing)
        ///   - callExpression (function calls)
        ///   - ( expression )   parenthesized sub-expressions
        /// @param ctx PrimaryExpressionContext
        /// @param ty type override
        /// @return The resulting Value
        mlir::Value parsePrimary( antlr4::ParserRuleContext* ctx, mlir::Type ty, LocationStack& ls );
    };
}    // namespace silly

// vim: et ts=4 sw=4
