#!/usr/bin/perl
use strict;
use warnings;
use File::Path qw(make_path);

my $dir = ".";
make_path($dir);

my $program = <<'PROG';
PRINT "hi";
PROG

sub generate {
    my ($name, $run_lines, $check_lines) = @_;

    my $filename = "$dir/$name.silly";
    open my $fh, '>', $filename or die "Cannot write $filename: $!";

    print $fh "// Auto-generated by generate-lit-emit-tests.pl\n";
    print $fh "// Tests -c --emit-* with -o and with --output-directory\n\n";

    print $fh "// RUN: cp %s %t.silly\n";
    print $fh $run_lines;
    print $fh "\n";
    print $fh $check_lines;
    print $fh "\n";
    print $fh $program;

    close $fh;
    print "Generated: $filename\n";
}

# ----------------------------------------------------------------------
# Tests with explicit -o
# ----------------------------------------------------------------------

generate("emit-llvm-o", <<'RUNS', <<'CHECKS');
// RUN: silly -c --emit-llvm %t.silly -o %t.ll
// RUN: head %t.ll | %FileCheck %s --check-prefix=CHECK-LL
// RUN: silly %t.ll -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-LL: define i32 @main()
// EXEC: hi
CHECKS

generate("emit-llvmbc-o", <<'RUNS', <<'CHECKS');
// RUN: silly -c --emit-llvmbc %t.silly -o %t.bc
// RUN: %LlvmDis %t.bc -o - | %FileCheck %s --check-prefix=CHECK-BC
// RUN: silly %t.bc -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-BC: define i32 @main()
// EXEC: hi
CHECKS

generate("emit-mlir-o", <<'RUNS', <<'CHECKS');
// RUN: silly -c --emit-mlir %t.silly -o %t.mlir
// RUN: head %t.mlir | %FileCheck %s --check-prefix=CHECK-MLIR
// RUN: silly %t.mlir -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-MLIR: func.func @main()
// EXEC: hi
CHECKS

generate("emit-mlirbc-o", <<'RUNS', <<'CHECKS');
// RUN: silly -c --emit-mlirbc %t.silly -o %t.mlirbc
// RUN: silly-opt -s %t.mlirbc | %FileCheck %s --check-prefix=CHECK-MLIR
// RUN: silly %t.mlirbc -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-MLIR: func.func @main()
// EXEC: hi
CHECKS

# ----------------------------------------------------------------------
# Tests with --output-directory (using -o inside the dir)
# ----------------------------------------------------------------------

generate("emit-llvm-outputdir", <<'RUNS', <<'CHECKS');
// RUN: mkdir -p %t.dir
// RUN: silly -c --emit-llvm %t.silly --output-directory %t.dir -o my.ll
// RUN: head %t.dir/my.ll | %FileCheck %s --check-prefix=CHECK-LL
// RUN: silly %t.dir/my.ll -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-LL: define i32 @main()
// EXEC: hi
CHECKS

generate("emit-llvmbc-outputdir", <<'RUNS', <<'CHECKS');
// RUN: mkdir -p %t.dir
// RUN: silly -c --emit-llvmbc %t.silly --output-directory %t.dir -o my.bc
// RUN: %LlvmDis %t.dir/my.bc -o - | %FileCheck %s --check-prefix=CHECK-BC
// RUN: silly %t.dir/my.bc -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-BC: define i32 @main()
// EXEC: hi
CHECKS

generate("emit-mlir-outputdir", <<'RUNS', <<'CHECKS');
// RUN: mkdir -p %t.dir
// RUN: silly -c --emit-mlir %t.silly --output-directory %t.dir -o my.mlir
// RUN: head %t.dir/my.mlir | %FileCheck %s --check-prefix=CHECK-MLIR
// RUN: silly %t.dir/my.mlir -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-MLIR: func.func @main()
// EXEC: hi
CHECKS

generate("emit-mlirbc-outputdir", <<'RUNS', <<'CHECKS');
// RUN: mkdir -p %t.dir
// RUN: silly -c --emit-mlirbc %t.silly --output-directory %t.dir -o my.mlirbc
// RUN: silly-opt -s %t.dir/my.mlirbc | %FileCheck %s --check-prefix=CHECK-MLIR
// RUN: silly %t.dir/my.mlirbc -o %t.exe
// RUN: %t.exe | %FileCheck %s --check-prefix=EXEC
RUNS
// CHECK-MLIR: func.func @main()
// EXEC: hi
CHECKS

print "\nAll 8 lit tests generated successfully!\n";
print "Run them with:\n";
print "    llvm-lit -v tests/lit/driver/*.silly\n";
